baseURL = 'https://example.org/'
languageCode = 'fr-FR'
title = 'Benoît Favrie'
theme = 'ananke'
featured_image = '/images/forest.jpg'
DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
enableRobotsTXT = true

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/beno%C3%AEt-favrie-44a37a203/"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/benoitfvr"
